// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxjpldsylrqmgrabzram.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4anBsZHN5bHJxbWdyYWJ6cmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTczNzcsImV4cCI6MjA3MjQ3MzM3N30.WNDpSBYVmRfGPaF0Z2X7keuatHt2Nbyu0aftzsPHi1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});